### ISSUE TITLE
Document allowed characters for data elements 

### ISSUE THREAD

**Issue by patrick-schweizer** [influxdata/docs-v2#1151]
I think the documentation it is not clear on what characters are allowed in the data elements.
E.g. I tried to store a tag named "a*" which didn't work, I assume a star is not allowed in the tag name?
It would be nice to have documentation on what is allowed and what not.

##### Relevant URLs
- https://v2.docs.influxdata.com/v2.0/reference/key-concepts/data-elements/#tag-key

##### What products and version are you using?
InfluxDB 2.0 documentation.

**Comment by sanderson** [comment]
@patrick-schweizer How are you writing the tag? Tags are just strings and should support a `*`. All data is converted to line protocol before being written to InfluxDB, so tag names are subject to line protocol restrictions. Because tag names are just strings, there shouldn't be any issue with using a `*`.

Accepted special characters are documented in the line protocol documentation, but we can definitely add links to the line protocol documentation in the [Data elements](https://v2.docs.influxdata.com/v2.0/reference/key-concepts/data-elements/) documentation.

Here are the relevant sections:

- [Quotes in line protocol](https://v2.docs.influxdata.com/v2.0/reference/syntax/line-protocol/#quotes)
- [Special characters in line protocol](https://v2.docs.influxdata.com/v2.0/reference/syntax/line-protocol/#special-characters)
- [Field and tag naming restrictions](https://v2.docs.influxdata.com/v2.0/reference/syntax/line-protocol/#naming-restrictions)

**Comment by patrick-schweizer** [comment]
@sanderson , thank you for the clarification.

I was trying to do something like that:
```
from(bucket:"opennms")
|> range(start:-5y)
|> filter(fn: (r) => (r.tagNameWithAsterix*=="something"))
|> keys()
```

and execute it via the java client.

**Comment by sanderson** [comment]
Oh, gotcha. That has to do with Flux syntax, not the actual storage of the tag. If you have special characters in a tag name, you need to use [bracket notation instead of dot-notation](https://v2.docs.influxdata.com/v2.0/query-data/get-started/syntax-basics/#objects).

```js
// ...
  |> filter(fn: (r) => (r["tagNameWithAsterix*"] == "something"))

**Comment by patrick-schweizer** [comment]
ahh, makes sense! Thank you!
