### ISSUE TITLE
InfluxDB 2.X vault access is no longer limited to OSS

### ISSUE THREAD

**Issue by darinfisher** [influxdata/docs-v2#1173]
The documentation for InfluxDB 2.0 incorrectly states that Vault access is limited to OSS.  This is no longer case as the ```secrets``` modules is available with Cloud 2.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/security/secrets/use-vault/
https://www.influxdata.com/blog/using-secret-stores-to-secure-flux-access/

##### What products and version are you using?
Cloud 2.0

**Comment by sanderson** [comment]
This doc was originally written when OSS was seen as the flagship. The content of the doc outlines how to setup a Vault server/cluster with OSS, which is why it has the OSS only flag. I think we have a few options here:

1. Update the title of the doc to something like: Use Vault with InfluxDB OSS
2. Remove the OSS-only flag and update the structure of the doc to create two sections: 
    - **Vault with InfluxDB Cloud:** Talks about Vault being the secret store for cloud two and how to use the secrets API with your Cloud 2 instance.
    - **Vault with InfluxDB OSS** Essentially keeps the current content of the doc and removes.
