### ISSUE TITLE
1.x Compatibility APIs and InfluxQL support

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#1184]
We are adding 1.x write compatibility API to InfluxDB Cloud 2.
We are also adding the 1.x query API support along with InfluxQL. 

Initially these will be Cloud only features.

These are available via API, there is no UI support and none is planned for our 2.0 native UI.

In terms of InfluxQL support -- there are some kinds of 1.x related queries which are not supported. We need to be clear that the queries that power Grafana and Chronograf dashboards are what is supported.

Please refer to this internal issue for more details:
https://github.com/influxdata/idpe/issues/7769

**Comment by sanderson** [comment]
I think to address cover this new feature, we need to do the following:

- [ ] Update the swagger.yml to include the InfluxQL support (this will be done by engineering)
- [ ] Add a new "Query InfluxDB with InfluxQL" doc under "Query data"
    - Include API request examples
    - Will client libraries support InfluxQL? @timhallinflux 
    - List limitations
- [ ] Port the InfluxQL documentation into Reference/Syntax. This is probably the most time consuming, but shouldn't hold us back from deploying the other content since it's already available in the 1.x docs. This InfluxQL documentation should only include functionality available in 2.0.
