### ISSUE TITLE
InfluxDB Stacks: lacking any real examples

### ISSUE THREAD

**Issue by 8none1** [influxdata/docs-v2#1230]
Stacks is a powerful feature of Influx and I am just starting to learn how to use it.  
I tend to use, for example, `influx stacks update -h` to find out the syntax but then rely on the docs to fill in the gaps.

Today I was trying to create a new Stack, and I wanted to know how to format the strings to pass in to the description.  i.e. If I want the description of the stack to be ```"This is the description of my stack, it has characters like commas and spaces so I probably need to use quotes round it"``` do I need quotes?

I want to be certain that I should put quotes around the string, but maybe that's not supported?  Will I break something in a production environment if I test it and get it wrong?  Will I end up with a broken description for ever more?
These are the sort of questions I expected to be answered by reading the docs, and see worked examples showing me what to do.

However, our docs say this:
```
Examples
# Initialize a stack with a name and description
influx stack init -n $STACK_NAME -d $STACK_DESCRIPTION

# Initialize a stack with a name and urls to associate with stack.
influx stack init -n $STACK_NAME -u $PATH_TO_TEMPLATE
```

The details that I would benefit from seeing in an example are missing and replaced with an environment variable which doesn't provide any example at all. 

I would like to see actual worked examples rather than abstracting away all the details in to an undefined environment variable.

I will happily add a PR to this issue once I better understand how to use this command.

##### Relevant URLs
https://v2.docs.influxdata.com/v2.0/reference/cli/influx/stacks/init/

##### What products and version are you using?
Cloud 2.0 at the end, `influx` from OSS to run the commands.

**Comment by timhallinflux** [comment]
Work with @russorat on this.

**Comment by noramullen1** [comment]
From Russ: I’m sharing this here because i think this gitops flow should have more prominence in the v2 docs but I’m not sure the best way to do it. Maybe we can move my repo internally and add a lot more information to it as an example?
Russ
I put together an example of how users and customers can leverage InfluxDB Stacks to build a GitOps workflow to automatically push changes merged to a Github repo to their cloud instance. Anyone who want’s to “leverage version control” for an influxdb resource could leverage this. It also shows how to use Github actions for CI.  Full content here: https://drive.google.com/drive/folders/1hMalR5dFrcc2zMiNhVIKv5B6TVwMD1wZ

**Comment by kelseiv** [comment]
Thank you @8none1 - added an example for how to format the strings to pass in the name and description of the stack. 
Also added a real life example on how to use stacks for a GitOps workflow, thanks to @russorat. 

One thing to clarify, the "stacks" docs examples were pulled from Russ's blog called "Make a GitOps Workflow Using _InfluxDB Templates_" 

....so that's how similar a template and stack are. When you apply an InfluxDB template, all resources in the template are added to your InfluxDB instance....and the "applied template" becomes a stack. The biggest difference between the two--when you apply a template, the template doesn't recognize resources that already exist in the instance; when you apply a stack, the stack does recognize existing resources.
