### ISSUE TITLE
Document the mosaic visualization type

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#1290]
PR: https://github.com/influxdata/influxdb/pull/19292

There is a new "mosaic" visualization type that looks like this:

![image](https://user-images.githubusercontent.com/181484/89956964-869a0c80-dbf3-11ea-9945-1931e1fb5622.png)

##### Relevant URLs
- https://v2.docs.influxdata.com/v2.0/visualize-data/visualization-types/

**Comment by TCL735** [comment]
Mosaic has several configuration properties similar to other visualizations and some that are unique. In Giraffe, the documentation of the configuration properties are similar. Notably, here is documentation for some of the properties:

- **x**: _string. **Required**._ The column name of the column that should be visualized on the x-axis. Note: in the current implementation, this is always __time_.

- **y**: _array[string, ...]. **Required**._ An array of column names that groups (or filters) data for the y-axis to visualize against a state or status (**fill**, see below).

- **yLabelColumns**: _array[string, ...] **Required**._ An array of column names that are used for labeling each tick in the y-axis and the header inside the legend. This allows the y-axis labels and legend header to be less verbose than naming all of the columns that used for **y**. **Does not affect data grouping**. This property is a subset of **y** (see above). Any elements in **yLabelColumns** that do not appear in **y** are ignored.

- **yLabelColumnSeparator**: _string. Optional._ Defaults to empty string (no separator) when not included. A string given to the CanvasRenderingContext2D.fillText function to use as a separator between the column names of the data for the y-axis.

- **fill**: _array[string]. **Required**._ An array with a single column name that is the state or status being visualized. This property is an array with a single element in order to remain consistent with other LayerConfigs where **fill** is always an array.

**Comment by timhallinflux** [comment]
dup of #1975 ?

**Comment by sanderson** [comment]
See more details about this feature in #1975
