### ISSUE TITLE
Links on InfluxDB key concept don't direct anywhere

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs-v2#1786]
Key terms table in InfluxDB key concepts don't direct anywhere.
Link: https://docs.influxdata.com/influxdb/v1.8/concepts/key_concepts/

![image](https://user-images.githubusercontent.com/32681364/98585042-87d2e800-227b-11eb-86d9-857f3d6349cd.png)

**Comment by pierwill** [comment]
Ah, interesting. Thanks @sjwang90. Should these point to the glossary, @kelseiv?

**Comment by kelseiv** [comment]
Thanks, @pierwill @sjwang90. 

Yes, @pierwill, let's add links to glossary. Let's remove the html table format (relic from 1.x) and add terms alphabetically in a bullet list. We can tweak the intro to apply:

Before diving into InfluxDB, it's good to get acquainted with some key concepts of the database. This document introduces key InfluxDB concepts and elements. To introduce the key concepts, we’ll cover how the following elements work together in InfluxDB:
...our bullet list in alphabetical order, linking to glossary


To gain a general understanding of our favorite time series database works, we recommend reading this document from start to finish.

(Since we’ll be linking terms to glossary, let’s remove “Check out the glossary if you prefer the cold, hard facts.”)
