### ISSUE TITLE
Removing or update VPC Peering note

### ISSUE THREAD

**Issue by bckeene** [influxdata/docs-v2#1809]
_Describe the issue here._
VPC isn't currently available (expected for H1/2021). I'm not sure if we should remove this entirely or the pricing language alone. It's caused confusion with a handful of new users who view the option as available today. 

##### Relevant URLs
https://docs.influxdata.com/influxdb/cloud/account-management/pricing-plans/#vpc-peering
##### What products and version are you using?
InfluxDB Cloud

**Comment by timhallinflux** [comment]
I don't want this to be removed.  Because NOT having it was also causing confusion.  

Folks are searching for VPC....and the point is, we want to gauge the demand. Having the conversation allows us to do that.  Being silent on this does not.  

If you want to suggest other language....please let us know.  But, do not remove.
