### ISSUE TITLE
Can't reproduce scatter example

### ISSUE THREAD

**Issue by cgfoed** [influxdata/docs-v2#1901]
correlation view isn't obtainable

##### Relevant URLs
https://docs.influxdata.com/influxdb/v2.0/visualize-data/visualization-types/scatter/#scatter-examples

##### What products and version are you using?
Version 2.0.0 (37cc047) running on Ubuntu 20.04

I was trying to get a plotted scatter-view, where "cpu" is on X and "mem" is on Y axis as shown of the right of your example output.
![scatter](https://docs.influxdata.com/img/influxdb/2-0-visualizations-heatmap-vs-scatter.png)

1st problem:
After trying with my own data for some time I installed Telegraf and used the ***exact same query** which is provided (just changed the bucket name)
I get the error message ` type error @21:21-21:24: found unexpected label _measurement`  if I include the mapping code:
`   |> map(fn: (r) => ({
      _value: r._value + 60.0,
      _time: r._time
      })
  )`

If I leave it out, the query will work.

2nd problem:
I can't figure out how to map "mem" to X and "cpu" data to the Y-axis or vice versa. The only option to choose from is "_value" or time.
I tried using the rename()-function to differentiate the two columns by name - but still could get a chart as shown in your doc.

**Comment by sanderson** [comment]
@cgfoed Add `r with` to the map call. This extends the record with the updated values and preserves the other columns not explicitly mapped in the map call. Without it, the output record only includes the columns explicitly mapped in the map call. I'll make sure this gets updated. 

```js
// Scale CPU usage
  |> map(fn: (r) => ({ r with
      _value: r._value + 60.0,
      _time: r._time
      })
  )
```

The image you included in this issue isn't what the visualization for the query in the guide looks like. That image is there to illustrate the difference between a scatterplot and a heatmap and how the scatterplot can "hide" points because it doesn't illustrate density well. That particular visualization was generated from sample data to illustrate that point.

To get a similar visualization with the mem and cpu data, drop unnecessary columns and pivot the data so the field values exist in each row:

```js
// ...

union(tables: [cpu, mem])
  |> keep(columns: ["_time", "_field", "_value"])
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
```
