### ISSUE TITLE
Search returns wrong version

### ISSUE THREAD

**Issue by caleb15** [influxdata/docs-v2#1902]
_Describe the issue here._
When searching for a term it returns results from v2 docs, even though I am on 1.8 docs

##### Relevant URLs
https://docs.influxdata.com/influxdb/v1.8

##### What products and version are you using?
influx v1.8

![image](https://user-images.githubusercontent.com/46505081/100646496-f04d3c00-32f2-11eb-9db5-716d8e885b7b.png)

**Comment by sanderson** [comment]
Thanks for reporting @caleb15. This is a known issue and one that I'm currently working of fixing. The problem is that that all the Flux documentation pages are in the v2.0 docs and the search service currently implemented on the docs requires us to open all of v2.0 just to make Flux docs available in the results.

The fix I'm working on is separating the Flux documentation from InfluxDB 2.0 and making them a standalone section of the docs.

**Comment by caleb15** [comment]
Thanks @sanderson !
