### ISSUE TITLE
Remove cli v1 auth page from cloud docs

### ISSUE THREAD

**Issue by russorat** [influxdata/docs-v2#2208]
https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/v1/auth/

these commands are not implemented for Cloud.

**Comment by sanderson** [comment]
There has been some discussion about this – these commands exist in the cloud doc because the commands exist in the CLI used to interact with cloud. Rather than remove commands, we've put notes about commands not working with Cloud. For example: https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/backup/
