### ISSUE TITLE
Micrometer 1.7 -- to support InfluxDB v2.x

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#2294]
https://github.com/micrometer-metrics/micrometer/pull/2113

This should work with both Cloud and OSS -- and should be added here once Micrometer 1.7 goes GA.  I believe they are working towards that this week.

https://docs.influxdata.com/influxdb/cloud/write-data/no-code/third-party/

**Comment by timhallinflux** [comment]
It appears that Micrometer outputs StatsD format which cannot be directly consumed by InfluxDB v2 (or Cloud).  Need some additional guidance on whether Telegraf is required to re-format the metrics or whether the improved integration as of Micrometer 1.7 includes a native line protocol implementation.  @bednar  it looks like the native line protocol support was added as part of your changes.  Do you have an example of the appropriate config?  It doesn't appear that this made it correctly into the micrometer docs...

**Comment by shakuzen** [comment]
Are you referring to these docs? https://micrometer.io/docs/registry/influx
Micrometer's Influx registry writes InfluxDB line protocol to InfluxDB directly. This has been supported since the Influx registry was introduced with Micrometer 1.0. Micrometer 1.7 added support for the v2 API and org/bucket/token configuration.
Shipping StatsD metrics to Telegraf is a separate option that can be achieved using the Statsd registry.

An easy way to get a sample application is generating a Spring Boot project with start.spring.io with the Web, Actuator, and Influx dependencies. Then add the configuration properties to `application.properties` for your InfluxDB `org`, `bucket`, and `token`. The `uri` defaults to `http://localhost:8086` but can also be configured.

```properties
management.metrics.export.influx.bucket=metrics
management.metrics.export.influx.org=org
management.metrics.export.influx.token=YOUR_TOKEN_HERE
```

If you would prefer I can upload something to GitHub you can run.

**Comment by timhallinflux** [comment]
Thanks @shakuzen --  I think my confusion comes from this example:

For example, Micrometer’s Spring Boot support binds properties prefixed with management.metrics.export.influx directly to the InfluxConfig:

Where the subsequent params only seem to show the InfluxDB v1 write API element.  The text says to set org, bucket and token for the v2...but I was hoping to see a rendered example using the v2 params.  

If you can add that to the doc example, we will simply add links/pointers to that. 

Thanks!
