### ISSUE TITLE
2.0.4 docker image data folder different from docs.

### ISSUE THREAD

**Issue by PaschalisSk** [influxdata/docs-v2#2385]
Unless I am missing something...

__Steps to reproduce:__
1. [Docs mention `/root/.influxdbv2` as data folder.](https://docs.influxdata.com/influxdb/v2.0/get-started/?t=Docker#persist-data-outside-the-influxdb-container)
2. `docker run influxdb:2.0.4` logs `service=storage-engine service=store path=/var/lib/influxdb2/engine/data`  and also `/root/.influxdbv2` is empty.

**Comment by danxmoran** [comment]
`/root/.influxdbv2` was the path used by the `quay.io` builds published for early 2.0.x releases. Looks like the docs haven't been updated since we restored the DockerHub build.

**Comment by sanderson** [comment]
We need to update this in the install/get-started guides. The filesystem layout is different depending on which Docker image you use (Dockerhub vs Quay.io). You can see the differences in the filesystem layout doc: 

https://docs.influxdata.com/influxdb/v2.0/reference/internals/file-system-layout/?t=Docker#file-system-layout

We should provide instructions for both in the install docs since they affect how mounts are configured in the Docker config, but we should also point users to the file system layout doc.

**Comment by pierwill** [comment]
Closed in #2468.
