### ISSUE TITLE
Clarify dateTime format for Annotated CSV

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#2486]
1. The dateTime format is somewhat confusing, e.g. instead of 2006-01-02, use distinct month and day numbers, e.g. 2006-01-15, and include a format designation, e.g. *yyyy-mm-dd*.
2. Does the specific use of "2006-01-02" have significance for my data? Apparently, it's only for the parser since my import failed when I tried other values, "2005-01-01".
3. "Custom timestamp formats" links to "Go time package" for examples, but the Go doc examples are difficult to find and not very helpful either.

**Comment by sanderson** [comment]
The `2006-01-02` format does have significance. This is due to how Go's date package formats dates. This article does a pretty good job of explaining why: https://yourbasic.org/golang/format-parse-string-time-date-example/.

I think we could pull in some of the core concepts from the link above into the annotated CSV documentation.

**Comment by jstirnaman** [comment]
What's confusing to me is that the format relies on that specific date, but mm and dd are ambiguous. Something more like this might have helped, but obviously we can't spell out all the cases:
e.g. If your dateTime is in "yyyy-mm-dd" ([ISO_8601](https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates)) then use dateTime:"2006-01-02"

**Comment by sanderson** [comment]
Yeah, I think we could definitely provide some examples.
