### ISSUE TITLE
Add Geo as a visualization graph type

### ISSUE THREAD

**Issue by pierwill** [influxdata/docs-v2#2658]
Do we need to add Geo as a visualization graph type here: https://docs.influxdata.com/influxdb/v2.0/visualize-data/visualization-types/

(Dev PR says this is a two-part process/addition for work on the UI/map widget, so maybe we’re not ready yet.)

(PS One to check for cloud too)

_Originally posted by @kelseiv in https://github.com/influxdata/docs-v2/pull/2654#discussion_r644972210_

**Comment by sanderson** [comment]
Maps will likely not be introduced into OSS for a while. Maps require an integration with a tile server which users will have to configure. This currently is not possible in OSS. This is likely a 2.1 (or even 2.2) feature.

**Comment by pierwill** [comment]
Thanks, @sanderson. This is now in the 2.1 milestone: https://github.com/influxdata/docs-v2/milestone/47

**Comment by seonglae** [comment]
There is map graph in UI but not in [2.1 docs](https://docs.influxdata.com/influxdb/v2.1/visualize-data/visualization-types/) 
and not working

Is this feature will be supported in 2.2? or how can I configure WMS like map server to visualize map graph?

**Comment by timhallinflux** [comment]
This is currently a Cloud-only feature.

**Comment by timhallinflux** [comment]
@wbaker85 can you review this?

**Comment by wbaker85** [comment]
Looks like the maps vis option showing up in UI on 2.1 is a bug - certainly not intended, since the OSS backend does not support this feature.

It started with this change in the UI: https://github.com/influxdata/ui/pull/2420

That was to remove the feature flags for the map visualization. It did add the "cloud only" logic where it would seem to be needed but that apparently didn't do the trick. It should be a pretty easy fix, I created an issue in `ui` for it: https://github.com/influxdata/ui/issues/3247

**Comment by pierwill** [comment]
Closing this since this feature is not yet available.
