### ISSUE TITLE
Review Enterprise 1.9 auth docs

### ISSUE THREAD

**Issue by pierwill** [influxdata/docs-v2#2803]
> @lesam @pierwill 
> Does it makes sense (and does it cover all bases) to replace the entire "User management" section here with a link to [Set up users with fine-grained authorization](https://docs.influxdata.com/enterprise_influxdb/v1.9/guides/fine-grained-authorization/)?
If so, let's do that, and then publish. If that doesn't cover all bases, let's create another doc issue to track this change specifically, and push out this PR, which addresses many broken links and starts folks on the auth path.

_Originally posted by @kelseiv in https://github.com/influxdata/docs-v2/pull/2778#discussion_r662517992_

**Comment by timhallinflux** [comment]
I think we need to re-organize the security sections of the docs under Administration.  There are a number of submenu items that I believe we need to collect together.  @kelseiv and I were looking at this earlier today.

**Comment by timhallinflux** [comment]
no... it does not cover all the bases....

If I break this down a bit more --- looking at what you can do with OSS and what you can do with Enterprise:

1. OSS supports the ability to setup users (READ/WRITE/ALL/ADMIN) permissions.  If you do nothing more, you have that permission for all DBs within the instance.

2. OSS ALSO allows for setting database level grants.  Meaning, within an instance, you can grant/deny access to the various databases within that instance (i.e. not a blanket grant....like in no. 1)

This is generally covered here :https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/#user-types-and-privileges

It appears that the only way to maintain these today is via InfluxQL commands.  This can be issued via the CLI (interactive session) or the Query API or via Chronograf.  However, Chronograf has specific UI pages which supports No. 1, but if you want to do No 2....you will need to submit individual InfluxQL queries through the Data Explorer (in the same way that you would use the CLI or Query API).

3. Enterprise shifts the number of user permission from 4 to 16.   These are covered here: https://docs.influxdata.com/enterprise_influxdb/v1.9/features/users/

These permissions can be set via the API and there are specific API calls to allow for User Management within InfluxDB Enterprise.  These are documented here: https://archive.docs.influxdata.com/enterprise_kapacitor/v1.5/administration/auth/#user-and-privilege-management-over-the-influxd-meta-api

Chronograf can again be used to set the individual user permissions when connected to InfluxDB Enterprise.

InfluxQL and the interactive mode using InfluxQL via the CLI cannot be used to set the Enterprise user permissions.  However, there is no distinction, warning or other indication that the user should NOT use these metaqueries for user management.

4. Enterprise appears to allows for TWO mechanisms for layering in addition permissions.  The first of which matches No. 2.  The mechanism exposed for OSS.  The other is the Fine Grained Authorization which is described here: https://docs.influxdata.com/enterprise_influxdb/v1.9/guides/fine-grained-authorization/

What is unclear?
1.  Customers who are upgrading from OSS to Enterprise.... what happens to the existing users and their permissions when the Enterprise upgrade is complete?

2.  What takes precedents the InfluxQL meta queries or the InfluxDB Meta API -- for user management?  Should a user be prevented from using the InfluxQL meta queries against InfluxDB Enterprise?

Both of these scenarios need some hands-on testing, walk-through, and exploration to understand the behavior so that we may document this really, really clearly.

My current guess is that only a subset of our customers are using the finer grained permissions offered by InfluxDB Enterprise and most resort to the broad permission set offered through the InfluxQL meta queries.
