### ISSUE TITLE
Reading Enterprise 1.9 from Cloud with flux `from` is supported

### ISSUE THREAD

**Issue by lesam** [influxdata/docs-v2#3073]
The cloud docs say:

```
from() cannot retrieve data from remote InfluxDB OSS 1.x or InfluxDB Enterprise 1.x data sources (including hosted, single-tenant InfluxDB Enterprise clusters).
```

But in fact we do support giving `host` as a 1.9 Enterprise Cluster

Also username and password authentication can be done via the 'token' argument, which is hinted at here: https://docs.influxdata.com/enterprise_influxdb/v1.9/guides/query_data/#query-data-with-flux but also works with `from`, by setting `token: "username:password"`

##### Relevant URLs
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/built-in/inputs/from/

TODO:

- [x] @mdevy-influxdata is going to confirm the `username:password` auth working from cloud into Enterprise 1.9 .

**Comment by mdevy-influxdata** [comment]
Confirmed that influxdb enterprise can be queried with authentication enabled.

`[root@influxdays` ~]# influx
Connected to http://localhost:8086 version 1.9.3-c1.9.3
InfluxDB shell version: unknown
>
>
>
> show databases
ERR: unable to parse authentication credentials
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
> quit
[root@influxdays ~]# influx -username admin -password admin
Connected to http://localhost:8086 version 1.9.3-c1.9.3
InfluxDB shell version: unknown
> show databases
name: databases
name
\----
_internal
telegraf


From the Cloud UI, without credentials the following error is displayed:
` unable to parse authentication credentials
`

After adding authentication, the query is successful.

`
from(bucket: "telegraf",host: "http://...:8086", token: "admin:admin")
`
