### ISSUE TITLE
Resolve security vulnerabilities in regex dependencies.

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/docs-v2#3154]
Dependabot detected regex libraries with vulnerabilities. Update dependencies if possible.

**Comment by jstirnaman** [comment]
Dismissed the alerts for now. I submitted them as issues to https://github.com/postcss/postcss-cli. The vulnerabilities are due to postcss-cli's dependencies. Everything else uses later versions of the regex packages. Options: 1) Since they're dev dependencies, ignore them for now until postcss-cli is updated or raises more problems, 2) remove dependencies from package.json and go back to manual installation.

**Comment by jdstrand** [comment]
This issue isn't in postcss-cli, but in `find-versions` pulled in from hugo-extended. Eg:
```
$ yarn why semver-regex
...
=> Found "semver-regex@2.0.0"
info Reasons this module exists
   - "hugo-extended#bin-wrapper#bin-version-check#bin-version#find-versions" depends on it
   - Hoisted from "hugo-extended#bin-wrapper#bin-version-check#bin-version#find-versions#semver-regex"
```

`find-versions` is updated for `semver-regex` in 5.0.0. `bin-version` 6.0.0 specifies `find-versions` 5.0.0. `bin-version-check` 5.0.0 specifies `bin-version` 6.0.0. `bin-wrapper` has not been updated for `bin-version` and `bin-version-check`: https://github.com/kevva/bin-wrapper/blob/master/package.json#L27. Unfortunately, `bin-wrapper` seems unmaintained: https://github.com/kevva/bin-wrapper/issues/79.

Fortunately, this commit to hugo-extended removes the `bin-wrapper` dependency: https://github.com/jakejarvis/hugo-extended/commit/d87c63f5d3d69c5398ce9bd6a0921f27b040ac0b#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519. This should resolve itself after upgrading to https://github.com/jakejarvis/hugo-extended/tree/v0.84.0. I suggest upgrading to at least https://github.com/jakejarvis/hugo-extended/commits/v0.92.0 since it resolves other dependencies.

**Comment by jdstrand** [comment]
@jstirnaman - hey, were you able to test the updated hugo-extended?

**Comment by XhmikosR** [comment]
@jstirnaman if you are confident about your updates happy to accept a PR upstream in hugo-bin. Or if someone's up to it, pick up my patches and release scoped versions https://github.com/kevva/bin-wrapper/issues/79#issuecomment-1011967842 so that everyone benefits from it :)

**Comment by XhmikosR** [comment]
BTW I have a testing branch with my forks https://github.com/fenneclab/hugo-bin/tree/dev-packages which fixes all security vulns:

```
C:\Users\xmr\Desktop\hugo-bin>npm i

> hugo-bin@0.80.1 postinstall
> rimraf vendor && node lib/install.js

Hugo binary successfully installed!

added 233 packages, and audited 234 packages in 16s

48 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
