### ISSUE TITLE
CLI docs show features for v2.1.0+ under a v2.0 URL

### ISSUE THREAD

**Issue by danxmoran** [influxdata/docs-v2#3200]
Our CLI docs show new features available in v2.1.0+ under a URL prefix of `v2.0`. This has confused some users who are getting the CLI via deb/rpm/docker (and are therefore stuck on the v2.0.x CLI for now).

##### Relevant URLs
- influxdata/influxdb#22610

**Comment by kelseiv** [comment]
Thanks, @danxmoran, I understand the confusion. The short story is we made some decisions that inadvertently affected the docs, and we agreed to live with these repercussions until 2.1 due to the amount of add'l work making interim updates required.

That said, we want to help folks....

@russorat @sanderson any thoughts on how to best clear up confusion/make effects more clear? A site-wide message? A note on top of all CLI pages? 

"_Historically, InfluxDB 2.0 included the CLI 2.0 and the CLI documentation was structured in tandem with the InfluxDB releases. Although we pulled the CLI from the InfluxDB 2.0.8+ package, we've continued to update the existing CLI docs to reflect the latest functionality available with the CLI 2.1 download<link>._ "

How easy would it be to identify changes that have happened since CLI 2.1 and highlight/identify them accordingly in the InfluxDB 2.0 docs?

**Comment by kelseiv** [comment]
fwiw, looks like our warning in InfluxDB 2.0.8 release notes didn't explicitly clarify in interim, the CLI docs were going to continue to be updated with InfluxDB 2.0 for the folks downloading the separate CLI package:
_Beginning in InfluxDB 2.1, the `influx` CLI will no longer be packaged with the release. Future versions of `influx` CLI will be released from the [influx-cli](https://github.com/influxdata/influx-cli) repository.

To adopt the new, separate `influx` CLI early, download the latest release from [GitHub](https://github.com/influxdata/influx-cli/releases/tag/v2.1.0) or from the [InfluxData Downloads portal](https://portal.influxdata.com/downloads/).Beginning in InfluxDB 2.1, the `influx` CLI will no longer be packaged with the release. Future versions of `influx` CLI will be released from the [influx-cli](https://github.com/influxdata/influx-cli) repository.

To adopt the new, separate `influx` CLI early, download the latest release from [GitHub](https://github.com/influxdata/influx-cli/releases/tag/v2.1.0) or from the [InfluxData Downloads portal](https://portal.influxdata.com/downloads/)._
