### ISSUE TITLE
Alphabetize functions

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#3220]
re @samhld `from` function feels buried; update to alphabetize Flux functions on the same level

**Comment by samhld** [comment]
I'm not sure if I'm alone in this or not but what I'm driving at is that, as a user, I would expect the function that is present in all Flux queries not to be nested under multiple categories.  I understand this function is "InfluxDB-specific" but so are all functions other than outputs until we have more inputs.  `from()` is InfluxDB-specific the same way as `filter()` is at this point, right?

Perhaps this is a larger issue for me and it's possible I just think about Flux differently but, in general, I think the organization of functions is somewhat difficult to follow.  Here's something I had proposed because it's how other familiar query languages do it:  https://github.com/influxdata/docs-v2/issues/1843#issuecomment-761229536

I also miss the "Transformations" and "Aggregations" sections.  That was intuitive to me.

I understand this layout was meant to follow the stdlib in Github but I think that's only beneficial to Flux developers/contributors, not to end users.

**Comment by samhld** [comment]
@sanderson Yep, I mentioned that at the end of my comment.  I suppose it's just a difference of opinion but I just have a hard time browsing that way.

**Comment by sanderson** [comment]
In the near future, all the stdlib docs will be auto-generated from Flux source code and the structure will match that of the standard library source code, so the structure won't change. But I'm open to suggestions on better utilizing categorizations. On thought I did have was actually breaking this doc (https://docs.influxdata.com/flux/v0.x/function-types/) into individual pages with the full list of functions that falls in each category. This would likely get close to the structure you're expecting and really just act as an alternate path into the stdlib docs.
