### ISSUE TITLE
Document top-level API endpoints

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#3414]
We need to document the following top level API endpoints:

#### "System" endpoints
- [x] `/ready`
- [x] `/health`
- [ ] `/pprof`
- [ ] `/pprof/all`

#### "Legacy" 
- [x] `/ping`
- [x] `/write` _(already documented as part of the 1.x compatibility API)_
- [x] `/query` _(already documented as part of the 1.x compatibility API)_

#### Docs
- [ ] `/docs`: Redocly page packaged with OSS

**Comment by jstirnaman** [comment]
@lesam I don't see paths defined for `/debug` or `/pprof` in the `openapi/src` or `openapi/contracts` https://github.com/influxdata/openapi/blob/3481defece3e8c70c47f21680857ac1a7c051a8b/contracts/ref/oss.yml

**Comment by lesam** [comment]
`debug/pprof` isn't so much a part of the API as a way to get debugging info that happens to share the same port. It is described here: https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/ - it's a default profiling server baked into go.

It isn't supported in Cloud.

On top of the vanilla API we also add

```
GET /debug/pprof/all?cpu=10s
GET /debug/pprof/all
```

The first one takes 10s and returns a tar.gz format binary file that includes the following profiles:

```
x profiles/cpu.pb.gz
x profiles/goroutine.pb.gz
x profiles/block.pb.gz
x profiles/mutex.pb.gz
x profiles/heap.pb.gz
x profiles/allocs.pb.gz
x profiles/threadcreate.pb.gz
```

The second returns all the profiles except the cpu profile, and is much faster.

**Comment by lesam** [comment]
I'm not opposed to adding them to the API spec but also I understand why it hasn't been done.

**Comment by jstirnaman** [comment]
@lesam Questions:
1. In OSS dev 0bd28f66bc, the links in `/debug/pprof` for each profile point to `/debug/[profile]` (returning a 404) instead of `/debug/pprof/[profile]` (returning data). e.g. The mutex link points to http://localhost:8086/debug/mutex?debug=1 instead of http://localhost:8086/debug/pprof/mutex?debug=1. Is that a bug? I haven't configured anything for it.
2. Is `profiles/cpu.pb.gz` from`GET /debug/pprof/all?cpu=10s` the same profile as `/debug/pprof/profile?seconds=10`?

**Comment by lesam** [comment]
1. - yes that's probably a bug
2. - yes

**Comment by jstirnaman** [comment]
Closed with [fix: tags and path cleanup](https://github.com/influxdata/openapi/commit/ea52b27e6d93e9a16b6bebeace57db51a3eb1a83)
