### ISSUE TITLE
Expand usage limits examples to make the output more usable for dashboards and tasks

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs-v2#3502]
Currently within InfluxDB Cloud, users can retrieve their usage limits using the [usage.limits() function.](https://docs.influxdata.com/flux/v0.x/stdlib/experimental/usage/limits/)

However, the output of that function is a JSON object and something that can directly be leveraged with other functions.

To successfully leverage the output, we require that JSON object to be parsed and mapped into something that could be used in dashboards cells or tasks using the [json.parse()](https://docs.influxdata.com/flux/v0.x/stdlib/experimental/json/parse/) function.

This proposal is to expand the example on the usage limits page to show how to convert the output into something which can be used (potentially via findRecord) within Dashboard cells (to display single stats for the individual rate limits) or tasks (in order to allow for an early warning check/alert).

**Comment by sanderson** [comment]
@timhallinflux In my attempt to do this, I haven't been able to successfully get a response from this function. I either get a 404 error, private IP error (in tools), or the data explorer dies...

Are we certain this function works as it's designed?

**Comment by timhallinflux** [comment]
@rickspencer3 and @bpalani interesting.  Have you tried a raw API call using a production account?

**Comment by sanderson** [comment]
I’ve tried with my personal free account. I don’t have access to a PAYG account. I assume the API would be available for both, since both have limits.

**Comment by gavincabbage** [comment]
@sanderson can you share the query you're running and the org and environment details?

I am able to use this function successfully in `stag03-us-east-1-aws` with a query like this

```
import "experimental/usage"
import "array"

response = usage.limits()

readLimit = response.rate.readKBs
writeLimit = response.rate.writeKBs
bucketLimit = response.bucket.maxBuckets

array.from(rows: [{
	readLimit: readLimit,
	writeLimit: writeLimit,
	bucketLimit: bucketLimit,
}])
```

which returns

```
,result,table,readLimit,writeLimit,bucketLimit
,_result,0,1000,17,2
```

If that example doesn't help clear up any syntax errors, etc. on your end, I can investigate your org and the specific environment in question after receiving the details above.

Thanks!

**Comment by sanderson** [comment]
@gavincabbage Ok, that does work. I've tested this in Cloud, OSS (remote call to Cloud), and in VS Code. I think it may have been a permissions issue, but rather than giving a 403 error, it gave a 404.

What permissions are required to hit this endpoint? Do you have to use an All-Access token?

- [See a related community question](https://community.influxdata.com/t/necessary-permissions-for-experimental-usage/23084)

**Comment by rickspencer3** [comment]
I got this error in tools:

```
 error calling function "limits" @4:12-4:26: error calling function "api" @usage.flux|181:16-181:109: url is not valid, it connects to a private IP
```
But it worked perfectly in my personal account on us-west.
![Uploading Screen Shot 2021-12-22 at 12.01.12 PM.png…]()

**Comment by gavincabbage** [comment]
@sanderson Yes often a lack of permissions returns a 404. This a security best practice, as it limits the amount of information we leak to an unauthorized user (e.g. if you hit the endpoint `/api/v2/<not_your_org_id>/limits` and get a 401 rather than a 404, that tells you that an org with that particular ID does in fact exist, which is none of your business and can open up other attack vectors).

The API requires permission to read the organization. Any user session or an all access token will have this access.

@rickspencer3 That does not surprise me as tools' IPs are likely on the Flux deny list. Tools is generally an odd duck w.r.t limits and usage. The usage API doesn't work there at all, for example, because we don't collect usage data there like we do in other clusters.

**Comment by gavincabbage** [comment]
@timhallinflux I might be missing the point of this question, but FYI `usage.limits()` calls `json.parse()` under the hood and the structure returned should be relatively easy to use, e.g. in my example above a limit can be accessed by `writeLimit = response.rate.writeKBs`.

Untested one-liner, but I think this would work for a dashboard cell for example:

```
array.from([{_value: usage.limits().rate.writeKBs}])
```

As for tasks etc. to preemptively alert when rate limits are approached but not yet exceeded, I worked through a few use cases like that John Corrigan and @Anaisdg when developing these functions. The task described [here](https://www.influxdata.com/influxdb-templates/influxdb-cloud-usage-dashboard/) should leverage `usage.limits()` to test whether the cardinality reported by `usage.from()` metrics is approaching the org's limit IIRC.

**Comment by sanderson** [comment]
@gavincabbage The request is just to improve the examples in the Flux documentation for this function. It's easy to do, I just wasn't having luck getting the function to work. Now I know why 😄 .
