### ISSUE TITLE
The date package examples should include using now

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/docs-v2#3779]
There are cases where the user will want to programmatically discover aspects of when the script ran. This is possible using the data package with now(), but this is not explained or documented.
```
import "date"
import "array"

y = date.year(t: now())
m = date.month(t: now())
d = date.monthDay(t: now())
array.from(rows: [{"year":y, "month":m, "day":d}])
```

Also how to use the truncate function. To get all data from the beginning of the year, for instance:
```
import "date"

s = date.truncate(t: now(), unit: 1y)

from(bucket: "my-bucket")
|> range(start: s)
```

##### Relevant URLs
- https://docs.influxdata.com/flux/v0.x/stdlib/date/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by rbetts** [comment]
I haven't tried this - but would expect something like:

`date.truncate(t: now(), unit: 1y)` to work.  From https://docs.influxdata.com/flux/v0.x/stdlib/date/truncate/

**Comment by jsternberg** [comment]
I think truncate is the intended method to get something from the beginning of the year. Truncate is also currently documented to only work with `1x` with `x` being the unit. I have recommended people to do things like `5m` or `15m` if their interval is equal to those. We should test and formally make that a documented and allowed thing since they pointed out to me that the documentation conflicted with my suggestion and I've never written a unit test to ensure that my suggestion was even valid.
