### ISSUE TITLE
Update API filename to reflect openapi

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#3810]
Per @StacieClark, the swagger.json file for the cloud API does not load into https://editor.swagger.io/ or Postman, and is different file than stored in openapi repo at /contracts/cloud.json. And calling the file swagger.json is a misnomer as we use openapi spec 3.0, rather than swagger. 

Please update the correct file/filename and/or address as needed for cloud and oss apis.

**Comment by jstirnaman** [comment]
@StacieClark Thanks for pointing this out. We no longer use [cloud.json](https://github.com/influxdata/openapi/blob/master/contracts/cloud.json), [cloud.yml](https://github.com/influxdata/openapi/blob/master/contracts/cloud.yml), oss.json, or oss.yml because they are incomplete. They don't include https://github.com/influxdata/openapi/tree/master/contracts/svc.

Instead, we use contracts/ref/ and then add some custom content. contracts/ref/ or our versions may have OpenAPI validation errors that conflict with swagger.io and Postman.

I'll look into the following:
- compatibility problems with swagger.io and Postman.
- pointing the download button at contracts/ref/ instead of docs.
- properly naming the downloaded specs.

**Comment by jstirnaman** [comment]
1. Remove the download button.
2. Add a link and description for the contract in openapi/contracts/ref/
