### ISSUE TITLE
Hyperlink to Execd readme is pointing to readme for Exec plugin

### ISSUE THREAD

**Issue by remiego** [influxdata/docs-v2#3863]
_Describe the issue here._

Both the anchor to the execd secion of the output plugins as well as the "view" link to the readme both refer to the Exec plugin
##### Relevant URLs
- https://docs.influxdata.com/telegraf/v1.21/plugins/
- _Provide other relevant URLs (project issues, community threads, etc.)_

**Comment by sanderson** [comment]
Fixing this now. I'm going to do the following:

- [ ] Update the heading IDs to include the plugin type. So instead of `https://docs.influxdata.com/telegraf/v1.21/plugins/#exec`, it would be `https://docs.influxdata.com/telegraf/v1.21/plugins/#input-exec`
- [ ] Update all links in the documentation that go to Telegraf plugins
- [ ] Fix the link for the
