### ISSUE TITLE
Change password instructions do not work

### ISSUE THREAD

**Issue by lwandzura** [influxdata/docs-v2#4038]
Received user feedback that the instructions for changing your password in the following doc do not work:

https://docs.influxdata.com/influxdb/v2.2/users/change-password/

**Comment by sanderson** [comment]
@lwandzura I think I know why, and the fix is included in the FAQ PR. To change a password, you have to use an operator token. We weren't calling that out before. I added it here: https://github.com/influxdata/docs-v2/pull/4040/files#diff-53a26bd7ddb2ba6d827468485c7cfec01423f83035dcbc1c05d1ded30185d0ddR25.

I'm going to go ahead and close this issue.
