### ISSUE TITLE
Clarify requirements needed to create a user

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#4517]
Page: https://docs.influxdata.com/influxdb/v2.4/users/create-user/
Feedback: The example doesn't explain how to enter these commands.  Entering from the command line fails and entering from within influx also fails.  Need to add some real working examples to show the actual syntax required

Add doc to clarify how to prevent the following error: `Error: failed to create user "newUser": 401 Unauthorized: write:users is unauthorized`

**Comment by lwandzura** [comment]
We need to clarify when to use the influx cli and when to run commands from the terminal command line - both are called command line interface, which makes this confusing.

**Comment by sanderson** [comment]
The reasons these examples don't work as is because they aren't providing the necessary credentials (they haven't created a CLI config and they aren't passing those credentials with the command). I think there's a few things we can do here:

- [ ] Add a note about using CLI configs to pass required authentication credentials. You can use the `{{< cli/influx-creds-note >}}` shortcode to drop a note in before the examples (like in the [CLI docs](https://docs.influxdata.com/influxdb/v2.4/reference/cli/influx/user/create/#authentication-credentials)).
- [ ] We need to clarify that creating a user requires an **Operator** token.

**Comment by peterreg** [comment]
I have been trying to get to the bottom of this myself. I have a suspicion that they are just glancing at the examples without noticing the configuration requirement. The feedback below is from Sept 25. The user included in the comment the command they tried to run. They look like they are just copying the example.

New user feedback!

Page: https://docs.influxdata.com/influxdb/v2.4/organizations/create-org/
Feedback: $ influx write influx org create -n my-org Error: must specify org ID or org name
