### ISSUE TITLE
Docker - configure-influxdb-with-docker

### ISSUE THREAD

**Issue by starox** [influxdata/docs-v2#4643]
_Describe the issue here._

Can't get server configuration following doc on docker install:

```
docker run \
  --rm influxdb:2.5.1 \
  influx server-config > config.yml
```

gives:

```
Error: failed to retrieve config: Get "http://localhost:8086/api/v2/config": dial tcp 127.0.0.1:8086: connect: connection refused
```

If I execute the command directly in the running container, I am unauthorized:

```
# docker exec -it influxdb  influx server-config > config.yml
root@home:/srv/influxdb# cat config.yml 
Error: failed to retrieve config: 401 Unauthorized: unauthorized access
root@home:/srv/influxdb# 
```

##### Relevant URLs
- https://docs.influxdata.com/influxdb/v2.5/install/?t=Docker#configure-influxdb-with-docker

**Comment by thormick** [comment]
+1 I ran into the exact same issue on 2.6.1. The command to get the configuration through a docker image seems to be just broken.

My workaround was to start a container named "influxdb" as per the instructions, then in another terminal run `docker exec -it influxdb influx setup` and `docker exec -it influxdb influx server-config > config.yml`.

If the documentation was correct this wouldn't be as much of an issue, but since it's not it was also very confusing that if `influx setup` isn't done then other commands just return "401 Unauthorized: unauthorized access".

https://docs.influxdata.com/influxdb/v2.6/install/?t=Docker#persist-data-outside-the-influxdb-container
