### ISSUE TITLE
example from docs rejected by influxdb

### ISSUE THREAD

**Issue by argonui** [influxdata/docs-v2#5017]
I'm trying to get CSV imports to work, and am following the example [0] most closely

When I attempt to upload this csv I get the following error: 
```
error in csv.from(): failed to read metadata: failed to read header row: wrong number of fields
```

[0] 
```
#group,false,false,false,false,false,false,false
#datatype,measurement,tag,tag,field,field,ignored,time
#default,,,,,,,
m,cpu,host,time_steal,usage_user,nothing,time
cpu,cpu1,host1,0,2.7,a,1482669077000000000
cpu,cpu1,host2,0,2.2,b,1482669087000000000
```

##### Relevant URLs
- https://docs.influxdata.com/influxdb/cloud/reference/syntax/annotated-csv/
- _Provide other relevant URLs (project issues, community threads, etc.)_

PS Why can't i copy/paste the error string?

**Comment by jstirnaman** [comment]
> PS Why can't i copy/paste the error string?
I'm not sure I understand.

**Comment by jstirnaman** [comment]
And the next example "mixing data types" should be:

```
#group,false,false,false,false,false,false,false,false,false
#datatype,measurement,tag,string,double,boolean,long,unsignedLong,duration,dateTime
#default,test,annotatedDatatypes,,,,,,
,m,name,s,d,b,l,ul,dur,time
,,,str1,1.0,true,1,1,1ms,1
,,,str2,2.0,false,2,2,2us,2020-01-11T10:10:10Z
```

**Comment by jstirnaman** [comment]
So, this is exposing my ignorance. Here's what I've gathered from other examples.

Annotated CSV in InfluxDB v2 query responses uses a comma to separate annotation name from annotation types. Flux also requires this syntax when parsing Annotated CSV.

See the example in https://docs.influxdata.com/influxdb/v2.0/query-data/flux/scalar-values/#sample-data. If I replace it with the following, it fails to parse:

```js
import "csv"

csv.from(csv: "
#datatype string,long,dateTime:RFC3339,string,string,double
#group false,true,false,true,true,false
#default ,,,,,
result,table,_time,location,_field,_value
0,2019-11-01T12:00:00Z,sfo,temp,65.1
0,2019-11-01T13:00:00Z,sfo,temp,66.2
0,2019-11-01T14:00:00Z,sfo,temp,66.3
0,2019-11-01T15:00:00Z,sfo,temp,66.8
1,2019-11-01T12:00:00Z,kjfk,temp,69.4
1,2019-11-01T13:00:00Z,kjfk,temp,69.9
1,2019-11-01T14:00:00Z,kjfk,temp,71.0
1,2019-11-01T15:00:00Z,kjfk,temp,71.2
2,2019-11-01T12:00:00Z,kord,temp,46.4
2,2019-11-01T13:00:00Z,kord,temp,46.3
2,2019-11-01T14:00:00Z,kord,temp,42.7
2,2019-11-01T15:00:00Z,kord,temp,38.9
")
|> yield()
```

When writing data, `influx` CLI and InfluxDB don't require those commas, nor do they fail if the commas are present. However, the commas (or lack thereof) must be consistent with the row data, or it will fail parsing.

_Note, this doesn't apply to InfluxDB v3, because v3 responses don't contain annotated CSV and v3 doesn't use Flux._
