### ISSUE TITLE
[Docker] Unable to generate the default configuration file on the host file system

### ISSUE THREAD

**Issue by deepaktunuguntla** [influxdata/docs-v2#5318]
When trying to generate the default configuration file following the docs, I get the following error

```
docker run --rm influxdb:2.7.4 influx server-config  > config.yml

Error: failed to retrieve config: Get "http://localhost:8086/api/v2/config": dial tcp 127.0.0.1:8086: connect: connection refused
```

Is it because of the missing token as mentioned here https://docs.influxdata.com/influxdb/v2/reference/cli/influx/server-config/?

##### Relevant URLs
- https://github.com/influxdata/docs-v2/issues/4841
- https://docs.influxdata.com/influxdb/v2/install/?t=Docker#configure-influxdb-with-docker
- https://docs.influxdata.com/influxdb/v2/reference/cli/influx/server-config/

**Comment by jstirnaman** [comment]
> Is it because of the missing token as mentioned here https://docs.influxdata.com/influxdb/v2/reference/cli/influx/server-config/?

Yes--this is a docs bug; the Docker instructions  jump ahead.

You need to follow the [Setup instructions](https://docs.influxdata.com/influxdb/v2/install/#set-up-influxdb) to create an _operator_ before you can run `influx server-config`. Then you can use the operator session or token to run other commands like generating an All-Access API token.

1. Before **Step 2** under https://docs.influxdata.com/influxdb/v2/install/#configure-influxdb-with-docker, you should have a running container with data persisting to your host directory.

2. In a new terminal, test that you can run CLI commands against the server in the running container--for example:

```sh
docker exec -it influxdb2 \
influx ping
```

_`ping`_ doesn't require token authentication, and the response should be `OK`.

3. Use the `influx setup` command to create an _operator_ with username and password. You can only run `setup` once and it starts an operator session so that you can use the username and password to generate API tokens and a config:

```sh
docker exec -it influxdb2 \ 
influx setup --help
```

The output is the following:

```sh
NAME:
    setup - Setup instance with initial user, org, bucket

USAGE:
    setup [command options] [arguments...]

COMMON OPTIONS:
   --host value                     HTTP address of InfluxDB [$INFLUX_HOST]
   --skip-verify                    Skip TLS certificate chain and host name verification [$INFLUX_SKIP_VERIFY]
   --configs-path value             Path to the influx CLI configurations [$INFLUX_CONFIGS_PATH]
   --active-config value, -c value  Config name to use for command [$INFLUX_ACTIVE_CONFIG]
   --http-debug                     
   --json                           Output data as JSON [$INFLUX_OUTPUT_JSON]
   --hide-headers                   Hide the table headers in output data [$INFLUX_HIDE_HEADERS]
   
OPTIONS:
   --username value, -u value   Name of initial user to create
   --password value, -p value   Password to set on initial user
   --token value, -t value      Auth token to set on the initial user [$INFLUX_TOKEN]
   --org value, -o value        Name of initial organization to create
   --bucket value, -b value     Name of initial bucket to create
   --retention value, -r value  Duration initial bucket will retain data, or 0 for infinite
   --force, -f                  Skip confirmation prompt
   --name value, -n value       Name to set on CLI config generated for the InfluxDB instance, required if other configs exist
   ```

Run an [initial setup](https://docs.influxdata.com/influxdb/v2/install/#run-influx-setup-without-user-interaction) to create the operator--for example:

```sh
docker exec -it influxdb2 \
influx setup \
  --username USERNAME \
  --password PASSWORD \
  --token TOKEN \
  --org ORGANIZATION_NAME \
  --bucket BUCKET_NAME \
  --force
```

4. Run `influx server-config`, create an All-Access authorization, etc.

If you already ran `influx setup` and you lost your operator credentials or need to create a new operator token, you can use the [`influxd recovery` server command](https://docs.influxdata.com/influxdb/v2/reference/cli/influxd/recovery/auth/).

**Comment by jstirnaman** [comment]
Duplicates #4643

**Comment by jstirnaman** [comment]
To amend my earlier reply, for most users, the `DOCKER_INFLUXDB_<NAME>` environment variables and associated setup are a better experience. See https://hub.docker.com/_/influxdb
