### ISSUE TITLE
Update left nav references and icons

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#927]
The newly deigned left nav will roll out with beta 8. We need to update all flow references to the left nav and update the `nav-icon` shortcode to accurately reflect the change.

![image](https://user-images.githubusercontent.com/181484/78800158-5bb75780-7978-11ea-9dfa-f6826721cdca.png)

##### Relevant URLs
- So many

**Comment by noramullen1** [comment]
Nora:

- [ ] Get started

- [ ] Write data

- [ ] Query data

- [ ] Process data

- [ ] Visualize data

- [ ] Manage organizations

Scott:

- [ ] Manage users (shouldn't need anything because of no UI options)

- [ ] Security and authorization

- [ ] Monitor and alert

- [ ] InfluxDB templates

- [ ] Back up and restore data
